### ISSUE TITLE
[Feature Request] Add explicit start and end time on Cell

### ISSUE THREAD

**Issue by n-d-r-d-g** [MrSunshyne/mauritius-power-outages#3]
Hi @MrSunshyne,

Thanks for this amazing tool 🎉.

I think a useful addition would be to display the start and end time of power cuts on the cards (see screenshot below)

![see screenshot](https://github.com/MrSunshyne/mauritius-power-outages/assets/96367205/7cfc9cbc-72cf-493f-b3bd-09d1731e3ed2)

I already have the code locally. Could you let me know if it's a feature you'd like to add? If so, which branch should I create my PR on?

**Comment by MrSunshyne** [comment]
We already have that information in the dataset, should be an easy implementation. I'll look into it !

**Comment by MrSunshyne** [comment]
PR https://github.com/MrSunshyne/mauritius-power-outages/pull/4

**Comment by MrSunshyne** [comment]
Implemented and merged! Thanks a lot for the visual suggestion.

**Comment by n-d-r-d-g** [comment]
Great, thanks for implementing this!
